### ISSUE TITLE
Making officially licensed keycap sets

### ISSUE THREAD

**Issue by minicap-cat** [cassidoo/ama#16]
Hi cassidoo! 

Do you have any advice, insights or pointers you're willing to share about making officially licensed keycap sets from your work on XDA/DSA Scrabble - or your keycap design experience in general? 

Context: I want to make an officially licensed keycap set of one of my favourite characters. I've designed a keycap set before ([KAM Sewing Tin](https://www.kamsewingtin.com/)) but am unsure about licensing. The character has other licensed merch outside of keycaps & a form for licensing inquiries on their website, but I'm worried they won't take me seriously if I just submit the form as a hobbyist designer 😰 and want to maximise my chances of getting the license!

Thank you!

**Comment by cassidoo** [comment]
I love your Sewing Tin set!! That's awesome!

Okay so firstly, they might take you more seriously than you think as long as you don't pitch yourself as a hobby designer. Sell yourself in that you should mention that you've designed and sold keycap sets before, and that you know what you're doing, and show the designs you have so far. After submitting that form... it's all about cold-calling honestly. For the Scrabble keycap sets, both times, I literally had to DM people on LinkedIn at the company until I was directed to the right people. A lot of folks will ask "have you filled out the form?" first, so it's worth doing it, but it's the human outreach that will push you through the queue much faster.

Also, if you're comfortable with it, talk about yourself as an entity rather than an indie designer! It helps to have that "persona" to be taken seriously (kind of like how book authors are taken more seriously with an agent). If you're not comfortable with that, reach out to folks at places like Clackeys, Drop, Omnitype, etc, who might be able to use their pull to help you out.

It definitely varies from company to company, but persistence really works! I hope this is helpful!

**Comment by minicap-cat** [comment]
Thank you so much for taking the time to respond & for your advice! It was very helpful - I feel a lot more prepared for the process than before. (And thank you for your kind words about Sewing Tin, too 🍪💙)
